// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers, deprecated_member_use
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:flutter_story_encoder/src/pigeon.g.dart';

abstract class TestStoryEncoderHostApi {
  static const MessageCodec<Object?> codec = StandardMessageCodec();
  Future<bool> start(EncoderConfig config);
  Future<bool> appendFrame(Uint8List rgbaData);
  Future<String?> finish();
  void cancel();
  static void setup(
    TestStoryEncoderHostApi? api, {
    BinaryMessenger? binaryMessenger,
  }) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.start',
        codec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        channel.setMockMessageHandler(null);
      } else {
        channel.setMockMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.start was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final EncoderConfig? arg_config = (args[0] as EncoderConfig?);
          assert(
            arg_config != null,
            'Argument for dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.start was null, expected non-null EncoderConfig.',
          );
          final bool output = await api.start(arg_config!);
          return <Object?>[output];
        });
      }
    }
  }
}
