// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.lucasveneno.flutter_story_encoder;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @NonNull
  protected static FlutterError createConnectionError(@NonNull String channelName) {
    return new FlutterError("channel-error",  "Unable to establish connection on channel: " + channelName + ".", "");
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class EncoderConfig {
    private @NonNull Long width;

    public @NonNull Long getWidth() {
      return width;
    }

    public void setWidth(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"width\" is null.");
      }
      this.width = setterArg;
    }

    private @NonNull Long height;

    public @NonNull Long getHeight() {
      return height;
    }

    public void setHeight(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"height\" is null.");
      }
      this.height = setterArg;
    }

    private @NonNull Long fps;

    public @NonNull Long getFps() {
      return fps;
    }

    public void setFps(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"fps\" is null.");
      }
      this.fps = setterArg;
    }

    private @NonNull Long bitrate;

    public @NonNull Long getBitrate() {
      return bitrate;
    }

    public void setBitrate(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"bitrate\" is null.");
      }
      this.bitrate = setterArg;
    }

    private @NonNull String outputPath;

    public @NonNull String getOutputPath() {
      return outputPath;
    }

    public void setOutputPath(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"outputPath\" is null.");
      }
      this.outputPath = setterArg;
    }

    private @NonNull Boolean addSilentAudio;

    public @NonNull Boolean getAddSilentAudio() {
      return addSilentAudio;
    }

    public void setAddSilentAudio(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"addSilentAudio\" is null.");
      }
      this.addSilentAudio = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    EncoderConfig() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      EncoderConfig that = (EncoderConfig) o;
      return width.equals(that.width) && height.equals(that.height) && fps.equals(that.fps) && bitrate.equals(that.bitrate) && outputPath.equals(that.outputPath) && addSilentAudio.equals(that.addSilentAudio);
    }

    @Override
    public int hashCode() {
      return Objects.hash(width, height, fps, bitrate, outputPath, addSilentAudio);
    }

    public static final class Builder {

      private @Nullable Long width;

      @CanIgnoreReturnValue
      public @NonNull Builder setWidth(@NonNull Long setterArg) {
        this.width = setterArg;
        return this;
      }

      private @Nullable Long height;

      @CanIgnoreReturnValue
      public @NonNull Builder setHeight(@NonNull Long setterArg) {
        this.height = setterArg;
        return this;
      }

      private @Nullable Long fps;

      @CanIgnoreReturnValue
      public @NonNull Builder setFps(@NonNull Long setterArg) {
        this.fps = setterArg;
        return this;
      }

      private @Nullable Long bitrate;

      @CanIgnoreReturnValue
      public @NonNull Builder setBitrate(@NonNull Long setterArg) {
        this.bitrate = setterArg;
        return this;
      }

      private @Nullable String outputPath;

      @CanIgnoreReturnValue
      public @NonNull Builder setOutputPath(@NonNull String setterArg) {
        this.outputPath = setterArg;
        return this;
      }

      private @Nullable Boolean addSilentAudio;

      @CanIgnoreReturnValue
      public @NonNull Builder setAddSilentAudio(@NonNull Boolean setterArg) {
        this.addSilentAudio = setterArg;
        return this;
      }

      public @NonNull EncoderConfig build() {
        EncoderConfig pigeonReturn = new EncoderConfig();
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        pigeonReturn.setFps(fps);
        pigeonReturn.setBitrate(bitrate);
        pigeonReturn.setOutputPath(outputPath);
        pigeonReturn.setAddSilentAudio(addSilentAudio);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(width);
      toListResult.add(height);
      toListResult.add(fps);
      toListResult.add(bitrate);
      toListResult.add(outputPath);
      toListResult.add(addSilentAudio);
      return toListResult;
    }

    static @NonNull EncoderConfig fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      EncoderConfig pigeonResult = new EncoderConfig();
      Object width = pigeonVar_list.get(0);
      pigeonResult.setWidth((Long) width);
      Object height = pigeonVar_list.get(1);
      pigeonResult.setHeight((Long) height);
      Object fps = pigeonVar_list.get(2);
      pigeonResult.setFps((Long) fps);
      Object bitrate = pigeonVar_list.get(3);
      pigeonResult.setBitrate((Long) bitrate);
      Object outputPath = pigeonVar_list.get(4);
      pigeonResult.setOutputPath((String) outputPath);
      Object addSilentAudio = pigeonVar_list.get(5);
      pigeonResult.setAddSilentAudio((Boolean) addSilentAudio);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class EncodingStats {
    private @NonNull Long framesProcessed;

    public @NonNull Long getFramesProcessed() {
      return framesProcessed;
    }

    public void setFramesProcessed(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"framesProcessed\" is null.");
      }
      this.framesProcessed = setterArg;
    }

    private @NonNull Double currentFps;

    public @NonNull Double getCurrentFps() {
      return currentFps;
    }

    public void setCurrentFps(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"currentFps\" is null.");
      }
      this.currentFps = setterArg;
    }

    private @NonNull Double progress;

    public @NonNull Double getProgress() {
      return progress;
    }

    public void setProgress(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"progress\" is null.");
      }
      this.progress = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    EncodingStats() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      EncodingStats that = (EncodingStats) o;
      return framesProcessed.equals(that.framesProcessed) && currentFps.equals(that.currentFps) && progress.equals(that.progress);
    }

    @Override
    public int hashCode() {
      return Objects.hash(framesProcessed, currentFps, progress);
    }

    public static final class Builder {

      private @Nullable Long framesProcessed;

      @CanIgnoreReturnValue
      public @NonNull Builder setFramesProcessed(@NonNull Long setterArg) {
        this.framesProcessed = setterArg;
        return this;
      }

      private @Nullable Double currentFps;

      @CanIgnoreReturnValue
      public @NonNull Builder setCurrentFps(@NonNull Double setterArg) {
        this.currentFps = setterArg;
        return this;
      }

      private @Nullable Double progress;

      @CanIgnoreReturnValue
      public @NonNull Builder setProgress(@NonNull Double setterArg) {
        this.progress = setterArg;
        return this;
      }

      public @NonNull EncodingStats build() {
        EncodingStats pigeonReturn = new EncodingStats();
        pigeonReturn.setFramesProcessed(framesProcessed);
        pigeonReturn.setCurrentFps(currentFps);
        pigeonReturn.setProgress(progress);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(framesProcessed);
      toListResult.add(currentFps);
      toListResult.add(progress);
      return toListResult;
    }

    static @NonNull EncodingStats fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      EncodingStats pigeonResult = new EncodingStats();
      Object framesProcessed = pigeonVar_list.get(0);
      pigeonResult.setFramesProcessed((Long) framesProcessed);
      Object currentFps = pigeonVar_list.get(1);
      pigeonResult.setCurrentFps((Double) currentFps);
      Object progress = pigeonVar_list.get(2);
      pigeonResult.setProgress((Double) progress);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return EncoderConfig.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return EncodingStats.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof EncoderConfig) {
        stream.write(129);
        writeValue(stream, ((EncoderConfig) value).toList());
      } else if (value instanceof EncodingStats) {
        stream.write(130);
        writeValue(stream, ((EncodingStats) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface StoryEncoderHostApi {

    void start(@NonNull EncoderConfig config, @NonNull Result<Boolean> result);

    void appendFrame(@NonNull byte[] rgbaData, @NonNull Result<Boolean> result);

    void finish(@NonNull NullableResult<String> result);

    void cancel();

    /** The codec used by StoryEncoderHostApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `StoryEncoderHostApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable StoryEncoderHostApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable StoryEncoderHostApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.start" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                EncoderConfig configArg = (EncoderConfig) args.get(0);
                Result<Boolean> resultCallback =
                    new Result<Boolean>() {
                      public void success(Boolean result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.start(configArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.appendFrame" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                byte[] rgbaDataArg = (byte[]) args.get(0);
                Result<Boolean> resultCallback =
                    new Result<Boolean>() {
                      public void success(Boolean result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.appendFrame(rgbaDataArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.finish" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                NullableResult<String> resultCallback =
                    new NullableResult<String>() {
                      public void success(String result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.finish(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.cancel" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.cancel();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  /** Generated class from Pigeon that represents Flutter messages that can be called from Java. */
  public static class StoryEncoderFlutterApi {
    private final @NonNull BinaryMessenger binaryMessenger;
    private final String messageChannelSuffix;

    public StoryEncoderFlutterApi(@NonNull BinaryMessenger argBinaryMessenger) {
      this(argBinaryMessenger, "");
    }
    public StoryEncoderFlutterApi(@NonNull BinaryMessenger argBinaryMessenger, @NonNull String messageChannelSuffix) {
      this.binaryMessenger = argBinaryMessenger;
      this.messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
    }

    /**
     * Public interface for sending reply.
     * The codec used by StoryEncoderFlutterApi.
     */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    public void onProgress(@NonNull EncodingStats statsArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onProgress" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(statsArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
    public void onError(@NonNull String messageArg, @NonNull String codeArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onError" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Arrays.asList(messageArg, codeArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
  }
}
