// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "pigeon.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface EncoderConfig ()
+ (EncoderConfig *)fromList:(NSArray<id> *)list;
+ (nullable EncoderConfig *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface EncodingStats ()
+ (EncodingStats *)fromList:(NSArray<id> *)list;
+ (nullable EncodingStats *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation EncoderConfig
+ (instancetype)makeWithWidth:(NSInteger )width
    height:(NSInteger )height
    fps:(NSInteger )fps
    bitrate:(NSInteger )bitrate
    outputPath:(NSString *)outputPath
    addSilentAudio:(BOOL )addSilentAudio {
  EncoderConfig* pigeonResult = [[EncoderConfig alloc] init];
  pigeonResult.width = width;
  pigeonResult.height = height;
  pigeonResult.fps = fps;
  pigeonResult.bitrate = bitrate;
  pigeonResult.outputPath = outputPath;
  pigeonResult.addSilentAudio = addSilentAudio;
  return pigeonResult;
}
+ (EncoderConfig *)fromList:(NSArray<id> *)list {
  EncoderConfig *pigeonResult = [[EncoderConfig alloc] init];
  pigeonResult.width = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.height = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.fps = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.bitrate = [GetNullableObjectAtIndex(list, 3) integerValue];
  pigeonResult.outputPath = GetNullableObjectAtIndex(list, 4);
  pigeonResult.addSilentAudio = [GetNullableObjectAtIndex(list, 5) boolValue];
  return pigeonResult;
}
+ (nullable EncoderConfig *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [EncoderConfig fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.width),
    @(self.height),
    @(self.fps),
    @(self.bitrate),
    self.outputPath ?: [NSNull null],
    @(self.addSilentAudio),
  ];
}
@end

@implementation EncodingStats
+ (instancetype)makeWithFramesProcessed:(NSInteger )framesProcessed
    currentFps:(double )currentFps
    progress:(double )progress {
  EncodingStats* pigeonResult = [[EncodingStats alloc] init];
  pigeonResult.framesProcessed = framesProcessed;
  pigeonResult.currentFps = currentFps;
  pigeonResult.progress = progress;
  return pigeonResult;
}
+ (EncodingStats *)fromList:(NSArray<id> *)list {
  EncodingStats *pigeonResult = [[EncodingStats alloc] init];
  pigeonResult.framesProcessed = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.currentFps = [GetNullableObjectAtIndex(list, 1) doubleValue];
  pigeonResult.progress = [GetNullableObjectAtIndex(list, 2) doubleValue];
  return pigeonResult;
}
+ (nullable EncodingStats *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [EncodingStats fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.framesProcessed),
    @(self.currentFps),
    @(self.progress),
  ];
}
@end

@interface nullPigeonPigeonCodecReader : FlutterStandardReader
@end
@implementation nullPigeonPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [EncoderConfig fromList:[self readValue]];
    case 130: 
      return [EncodingStats fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullPigeonPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullPigeonPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[EncoderConfig class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[EncodingStats class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullPigeonPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullPigeonPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullPigeonPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullPigeonPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetPigeonCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullPigeonPigeonCodecReaderWriter *readerWriter = [[nullPigeonPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpStoryEncoderHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<StoryEncoderHostApi> *api) {
  SetUpStoryEncoderHostApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpStoryEncoderHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<StoryEncoderHostApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.start", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startConfig:completion:)], @"StoryEncoderHostApi api (%@) doesn't respond to @selector(startConfig:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        EncoderConfig *arg_config = GetNullableObjectAtIndex(args, 0);
        [api startConfig:arg_config completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.appendFrame", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(appendFrameRgbaData:completion:)], @"StoryEncoderHostApi api (%@) doesn't respond to @selector(appendFrameRgbaData:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FlutterStandardTypedData *arg_rgbaData = GetNullableObjectAtIndex(args, 0);
        [api appendFrameRgbaData:arg_rgbaData completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.finish", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(finishWithCompletion:)], @"StoryEncoderHostApi api (%@) doesn't respond to @selector(finishWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api finishWithCompletion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.cancel", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(cancelWithError:)], @"StoryEncoderHostApi api (%@) doesn't respond to @selector(cancelWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api cancelWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface StoryEncoderFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation StoryEncoderFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)onProgressStats:(EncodingStats *)arg_stats completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onProgress", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPigeonCodec()];
  [channel sendMessage:@[arg_stats ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onErrorMessage:(NSString *)arg_message code:(NSString *)arg_code completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onError", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetPigeonCodec()];
  [channel sendMessage:@[arg_message ?: [NSNull null], arg_code ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

