// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class EncoderConfig;
@class EncodingStats;

@interface EncoderConfig : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithWidth:(NSInteger )width
    height:(NSInteger )height
    fps:(NSInteger )fps
    bitrate:(NSInteger )bitrate
    outputPath:(NSString *)outputPath
    addSilentAudio:(BOOL )addSilentAudio;
@property(nonatomic, assign) NSInteger  width;
@property(nonatomic, assign) NSInteger  height;
@property(nonatomic, assign) NSInteger  fps;
@property(nonatomic, assign) NSInteger  bitrate;
@property(nonatomic, copy) NSString * outputPath;
@property(nonatomic, assign) BOOL  addSilentAudio;
@end

@interface EncodingStats : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithFramesProcessed:(NSInteger )framesProcessed
    currentFps:(double )currentFps
    progress:(double )progress;
@property(nonatomic, assign) NSInteger  framesProcessed;
@property(nonatomic, assign) double  currentFps;
@property(nonatomic, assign) double  progress;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetPigeonCodec(void);

@protocol StoryEncoderHostApi
- (void)startConfig:(EncoderConfig *)config completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)appendFrameRgbaData:(FlutterStandardTypedData *)rgbaData completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)finishWithCompletion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)cancelWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpStoryEncoderHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<StoryEncoderHostApi> *_Nullable api);

extern void SetUpStoryEncoderHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<StoryEncoderHostApi> *_Nullable api, NSString *messageChannelSuffix);


@interface StoryEncoderFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)onProgressStats:(EncodingStats *)stats completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onErrorMessage:(NSString *)message code:(NSString *)code completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
