// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Wraps an API response for transport over Pigeon channels.
List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Configuration parameters for the native video encoder.
///
/// Pass an instance of this class to [FlutterStoryEncoder.start] to configure
/// the hardware encoder before appending frames.
class EncoderConfig {
  /// Creates an [EncoderConfig] with the given encoding parameters.
  EncoderConfig({
    required this.width,
    required this.height,
    required this.fps,
    required this.bitrate,
    required this.outputPath,
    required this.addSilentAudio,
  });

  /// The target width of the exported video, in pixels.
  int width;

  /// The target height of the exported video, in pixels.
  int height;

  /// The target frame rate of the exported video (e.g. 30 or 60).
  int fps;

  /// The target bitrate in bits per second (e.g. `10000000` for 10 Mbps).
  int bitrate;

  /// The absolute file system path for the output `.mp4` file.
  String outputPath;

  /// Whether to include a silent AAC audio track for broader player compatibility.
  bool addSilentAudio;

  /// Encodes this config for Pigeon channel transport.
  Object encode() {
    return <Object?>[width, height, fps, bitrate, outputPath, addSilentAudio];
  }

  /// Decodes an [EncoderConfig] from a Pigeon channel response.
  static EncoderConfig decode(Object result) {
    result as List<Object?>;
    return EncoderConfig(
      width: result[0]! as int,
      height: result[1]! as int,
      fps: result[2]! as int,
      bitrate: result[3]! as int,
      outputPath: result[4]! as String,
      addSilentAudio: result[5]! as bool,
    );
  }
}

/// Real-time statistics emitted by the native encoder during an encoding session.
///
/// Delivered via [FlutterStoryEncoder.start]'s `onProgress` callback.
class EncodingStats {
  /// Creates an [EncodingStats] snapshot.
  EncodingStats({
    required this.framesProcessed,
    required this.currentFps,
    required this.progress,
  });

  /// Total number of frames successfully encoded and written to disk.
  int framesProcessed;

  /// Current encoder throughput in frames per second.
  double currentFps;

  /// Estimated encoding progress from `0.0` (start) to `1.0` (complete).
  double progress;

  /// Encodes this stats object for Pigeon channel transport.
  Object encode() {
    return <Object?>[framesProcessed, currentFps, progress];
  }

  /// Decodes an [EncodingStats] from a Pigeon channel response.
  static EncodingStats decode(Object result) {
    result as List<Object?>;
    return EncodingStats(
      framesProcessed: result[0]! as int,
      currentFps: result[1]! as double,
      progress: result[2]! as double,
    );
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is EncoderConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is EncodingStats) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return EncoderConfig.decode(readValue(buffer)!);
      case 130:
        return EncodingStats.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Low-level Pigeon API for calling native encoder methods from Dart.
///
/// Use [FlutterStoryEncoder] instead of this class directly.
class StoryEncoderHostApi {
  /// Constructor for [StoryEncoderHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  StoryEncoderHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Starts the native encoding session with the given [config].
  ///
  /// Returns `true` if the encoder was successfully initialized.
  Future<bool> start(EncoderConfig config) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.start$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Appends a raw RGBA frame to the encoding session.
  ///
  /// Returns `true` if the frame was accepted, or `false` if the encoder is
  /// busy (backpressure). In that case, retry after a short delay.
  Future<bool> appendFrame(Uint8List rgbaData) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.appendFrame$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[rgbaData]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Finalizes the video, flushes buffers, and returns the output file path.
  Future<String?> finish() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.finish$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  /// Cancels the current encoding session and releases native resources.
  Future<void> cancel() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_story_encoder.StoryEncoderHostApi.cancel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Pigeon callback API for receiving events from the native encoder.
///
/// Implement this to receive progress and error events. Use [FlutterStoryEncoder]
/// which handles the registration automatically.
abstract class StoryEncoderFlutterApi {
  /// @nodoc
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called during encoding with the latest [EncodingStats].
  void onProgress(EncodingStats stats);

  /// Called when the native encoder encounters a fatal error.
  ///
  /// [message] is a human-readable description and [code] is a machine-readable
  /// error code for programmatic handling.
  void onError(String message, String code);

  static void setUp(
    StoryEncoderFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onProgress was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final EncodingStats? arg_stats = (args[0] as EncodingStats?);
          assert(
            arg_stats != null,
            'Argument for dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onProgress was null, expected non-null EncodingStats.',
          );
          try {
            api.onProgress(arg_stats!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onError$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onError was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_message = (args[0] as String?);
          assert(
            arg_message != null,
            'Argument for dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onError was null, expected non-null String.',
          );
          final String? arg_code = (args[1] as String?);
          assert(
            arg_code != null,
            'Argument for dev.flutter.pigeon.flutter_story_encoder.StoryEncoderFlutterApi.onError was null, expected non-null String.',
          );
          try {
            api.onError(arg_message!, arg_code!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
